### ISSUE TITLE
[EPIC] Climate Change dashboard app

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/carbondoomsday#1]
## Tasks

* [x] discussion, analysis and research on existing dashboards
* [x] fix issue with raw data - #2 
* [x] research old carbondoomsday and see what we can reuse
* [x] design - #3 
* [x] implementation
* [x] deployment

## Analysis

Old carbondoomsday - https://carbon-inferno-agkbnxwcyw.now.sh/
Backend repo - https://git.coop/decentral1se/carbondoomsday
Frontend - https://github.com/giving-a-fuck-about-climate-change/carbon-inferno

We want to reuse old frontend if possible or imitate the old design. The old frontend is React but is it compatible/easy-to-use around datapackages? We have showcase-js which is also React and written specifically for datapackages - https://github.com/datahq/frontend-showcase-js 

Actions:

* [x] fork showcase-js and plug in https://datahub.io/core/co2-ppm-daily
* [x] make sure we have all required figures along with raw data
  * [x] "Global CO2 level"
  * [x] "In the past five years"
  * [x] "In the past five years (%)"

**Comment by titojankowski** [comment]
How can we make most use of the heavily-starred original repo?
https://github.com/giving-a-fuck-about-climate-change/carbondoomsday

In the meantime I've updated the CDD repo to link to this one.

**Comment by titojankowski** [comment]
One idea: force push this repo to the original.

**Comment by rufuspollock** [comment]
FIXED.

**Comment by titojankowski** [comment]
Looking great Rufus! Hello from 423 PPM 😆
