### ISSUE TITLE
Fix co2-ppm-daily dataset

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/carbondoomsday#2]
Auto updates are broken on https://datahub.io/core/co2-ppm-daily which we need for this project.

## Acceptance criteria

* [x] The data is updated on a daily basis

## Tasks

* [x] research why Travis isn't able to update the data
  * already done before by @svetozarstojkovic - https://gitlab.com/datopian/get-the-data/issues/22#note_133781393
* [x] implement alternative, e.g., using datahub factory - https://github.com/datahq/factory

**Comment by rufuspollock** [comment]
@anuveyatsu the issue is just that on some days the retrieval from ftp breaks. If that doesn't happen too often we could live with it.

**Comment by rufuspollock** [comment]
@svetozarstojkovic how often is it failing? Every day or only sometimes?

**Comment by svetozarstojkovic** [comment]
So far every 2-3 days co2-ppm-daily was passing, based on history in cron jobs in travis, one option is to leave it like this, other is to continue investigating why is it failing (probably the server is overloaded or something like that)

**Comment by svetozarstojkovic** [comment]
This issue has been fixed, please check.

**Comment by anuveyatsu** [comment]
FIXED:

If compare https://datahub.io/core/co2-ppm-daily/v/239 vs https://datahub.io/core/co2-ppm-daily/v/240

```
2019-06-26,413.5
2019-06-27,412.98
2019-06-28,413.05
2019-06-29,413.01
```

vs

```
2019-06-27,412.98
2019-06-28,413.05
2019-06-29,413.01
2019-06-30,413.52
```
