### ISSUE TITLE
UX review on 31 Jan am version

### ISSUE THREAD

**Issue by rufuspollock** [datopian/carbondoomsday#6]
Aside: do we want to use plotly here vs e.g. vega given what we want?

## Tasks

**Design**

* [x] Should have no title on the chart
* [x] Chart in red with filled like original
* [x] Changer is not a dropdown but horizontal listed options like on original (better UX as user can immediately see options)
* [ ] Text around headline figures needs to be fuller e.g. "+13.52 in last five years" rather than just "+13.25 change"
* [x] Text size of headline figure should be bigger - compare with old version.
* [ ] No hover on points anymore (with vega)

**Data**

* [x] Calculated numbers look wrong
  * [x] e.g. change is negative when should be positive
  * [x] percentage should be multiplied by 100

![image](https://user-images.githubusercontent.com/180658/52042979-6f765b00-2536-11e9-93c1-2c58d64807d5.png)

![image](https://user-images.githubusercontent.com/180658/52043011-86b54880-2536-11e9-9139-519f3bdb9096.png)

**Comment by titojankowski** [comment]
Any plans to add the cursor when you mouse over the data from the original CDD?

**Comment by titojankowski** [comment]
In case helpful, attached is a screenshot from what the site looked like on 4/11/2018:

![carbon doomsday screenshot](https://user-images.githubusercontent.com/129060/52192998-c1063a80-2801-11e9-9469-f7378ccf4fc6.png)

**Comment by rufuspollock** [comment]
@titojankowski the cursor hover was there before but seems to have got lost in move to vega - i've now added this to checklist at top /cc @anuveyatsu

**Comment by rufuspollock** [comment]
FIXED.
